const {chromium}=require('playwright'),path=require('path'),LIB=path.resolve('node_modules/vue/dist/vue.global.prod.js');
(async()=>{const b=await chromium.launch(),R=[];const ok=(c,m)=>{R.push(c);console.log((c?'PASS ':'FAIL ')+m)};
const ctx=await b.newContext({viewport:{width:1280,height:900}}),p=await ctx.newPage(),errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.addInitScript(()=>Object.defineProperty(window,'VueCM',{get(){},set(){}}));await p.route('**/*',r=>/cdn\.jsdelivr/.test(r.request().url())?r.fulfill({path:LIB,contentType:'text/javascript'}):r.continue());
await p.goto('file://'+path.resolve('vue3-course.html'));await p.waitForTimeout(800);
const S='[data-ex="phenoFilter"] textarea[data-k="js"]',T='[data-ex="phenoFilter"] textarea[data-k="tpl"]';
await p.$eval(S,e=>e.scrollIntoView());await p.waitForTimeout(600);
const set=async(sel,v,pos)=>{await p.$eval(sel,(e,[v,pos])=>{e.value=v;e.dispatchEvent(new Event('input'));e.focus();e.setSelectionRange(pos,pos)},[v,pos])};
const val=sel=>p.$eval(sel,e=>[e.value,e.selectionStart,e.selectionEnd]);
const hlOk=sel=>p.$eval(sel,e=>e.previousElementSibling.textContent.replace(/\n$/,'')===e.value);
await set(S,'',0);await p.keyboard.type('function f(');let [v,c]=await val(S);ok(v==='function f()'&&c===11,'自动补全括号 '+JSON.stringify(v));
await p.keyboard.type(')');[v,c]=await val(S);ok(v==='function f()'&&c===12,'输入右括号时跳过 '+JSON.stringify(v));
await p.keyboard.type(' {');await p.keyboard.press('Enter');[v,c]=await val(S);ok(v==='function f() {\n  \n}'&&c===17,'括号中回车后缩进 '+JSON.stringify(v));
await p.keyboard.type("x = '");[v,c]=await val(S);ok(v.includes("x = ''"),'引号配对 '+JSON.stringify(v));
await p.keyboard.press('Backspace');[v]=await val(S);ok(v.includes('x = \n')||v.includes('x = '+'\n'),'退格删除成对引号 '+JSON.stringify(v));
ok(await hlOk(S),'高亮层同步');
await set(S,'a\nb',0);await p.keyboard.press('Tab');[v]=await val(S);ok(v==='  a\nb','Tab 插入两个空格 '+JSON.stringify(v));ok(await hlOk(S),'Tab 后高亮同步');
await p.keyboard.press('Control+z');[v]=await val(S);ok(v==='a\nb','Ctrl+Z 撤销 '+JSON.stringify(v));
await p.$eval(S,e=>e.setSelectionRange(0,3));await p.keyboard.press('Tab');[v]=await val(S);ok(v==='  a\n  b','多行缩进 '+JSON.stringify(v));
await p.keyboard.press('Shift+Tab');[v]=await val(S);ok(v==='a\nb','多行减少缩进 '+JSON.stringify(v));
await p.$eval(S,e=>e.setSelectionRange(0,3));await p.keyboard.press('Control+/');[v]=await val(S);ok(v==='// a\n// b','注释 '+JSON.stringify(v));
await p.keyboard.press('Control+/');[v]=await val(S);ok(v==='a\nb','取消注释 '+JSON.stringify(v));
await set(T,'<ul></ul>',4);await p.keyboard.press('Enter');[v]=await val(T);ok(v==='<ul>\n  \n</ul>','模板标签中回车 '+JSON.stringify(v));
await set(T,'<p class',8);await p.keyboard.type('="');[v]=await val(T);ok(v==='<p class=""','模板属性引号 '+JSON.stringify(v));
await p.keyboard.press('Escape');await p.keyboard.press('Tab');ok(await p.evaluate(()=>document.activeElement.dataset.k)!=='tpl','Esc 后 Tab 离开编辑器');
// 错误行
await set(S,'const a = 1\nnull.x\nreturn {}',0);await p.click('[data-ex="phenoFilter"] [data-a="run"]');await p.waitForTimeout(500);
const bad=await p.$eval(S,e=>{const b=e.previousElementSibling.querySelector('.badln');return b&&[e.dataset.bad,b.getBoundingClientRect().top-e.getBoundingClientRect().top]});ok(bad&&bad[0]==='2','错误行标记 '+JSON.stringify(bad)+' '+await p.textContent('[data-ex="phenoFilter"] .ex-err'));
await p.click('[data-ex="phenoFilter"] .ex-err');ok(await p.$eval(S,e=>document.activeElement===e&&e.selectionStart===12),'点击错误跳到该行');
await p.$eval(S,e=>e.closest('.ex').scrollIntoView());await p.screenshot({path:'ed.png'});
ok(!errs.length,'无页面错误 '+errs);console.log('合计',R.length,'通过',R.filter(Boolean).length);await b.close()})();
